### PR TITLE
Update USD.yml

### PR DESCRIPTION
**Pull request by rumblestrut**
This fixes handling of the United States from AS (American Samoa) to US.

### CODE REVIEW

**Comment by bartfeenstra** [comment]
Thanks for submitting this PR! Can you explain why this change is needed?

**Comment by rumblestrut** [comment]
I'm working on a project where USD was being displayed as "AS" instead of "US." The correct ISO 3166 code for the United States is just "US."

**Comment by bartfeenstra** [comment]
AS is American Samoa, which has its own ISO 3166 code. USA usage of the USD is a little lower down in USD.yml.

**Comment by rumblestrut** [comment]
Oops. My mistake. I guess back to the drawing board to figure out why my view is displaying AS instead of US then.

**Comment by bartfeenstra** [comment]
No problem :) It's the first usage mentioned in the file, maybe that's why. You'll probably have to loop through the values and compare country codes to get the usage you need for the locale you're working with.

**Pull request closed without merging**
